-- GENERATED by tools/build_evolutions_extra.py -- do not edit.
-- Evolutions data/species.lua could not express, now mapped.
--
-- Gen 1 has five stones, so every later stone maps onto the closest one:
--   sun -> LEAF, dusk/dawn/shiny/peat -> MOON, ice -> WATER.
-- Friendship, held items, time of day, known moves and locations do not
-- exist in Gen 1 at all, so those become plain LEVEL evolutions at
-- commonly-cited levels rather than being dropped: baby forms early
-- (Pichu 10, Togepi 12), mid-line upgrades where the species is actually
-- usable (Yanma 33, Gligar 38), Feebas late at 40 so Milotic stays a payoff.
--
-- One route per target: a stone beats a level when both existed, because two
-- paths to the same species reads as a bug in the dex.
--
-- Targets past dex 649 are DROPPED, not mapped: evolutions[].species is an
-- f.id("pokemon") reference, so a Gen 8/9 target is a dangling ref that fails
-- the post-merge cross-check and takes the whole mod down.  Dropped here:
--   BASCULIN->BASCULEGION, BISHARP->KINGAMBIT, DUNSPARCE->DUDUNSPARCE,
--   GIRAFARIG->FARIGIRAF, QWILFISH->OVERQWIL, SNEASEL->SNEASLER,
--   STANTLER->WYRDEER, URSARING->URSALUNA, YAMASK->RUNERIGUS
--
-- Kept separate from data/species.lua so it stays reviewable rather than
-- vanishing into 500 KB of generated data.
return {
  AIPOM = { { method = "LEVEL", level = 32, species = "AMBIPOM" } },
  AZURILL = { { method = "LEVEL", level = 10, species = "MARILL" } },
  BONSLY = { { method = "LEVEL", level = 15, species = "SUDOWOODO" } },
  BUDEW = { { method = "LEVEL", level = 12, species = "ROSELIA" } },
  BUNEARY = { { method = "LEVEL", level = 16, species = "LOPUNNY" } },
  CHINGLING = { { method = "LEVEL", level = 12, species = "CHIMECHO" } },
  CLEFFA = { { method = "LEVEL", level = 10, species = "CLEFAIRY" } },
  COTTONEE = { { method = "ITEM", level = 1, item = "LEAF_STONE", species = "WHIMSICOTT" } },
  DARUMAKA = { { method = "ITEM", level = 1, item = "WATER_STONE", species = "DARMANITAN" } },
  EELEKTRIK = { { method = "ITEM", level = 1, item = "THUNDER_STONE", species = "EELEKTROSS" } },
  FEEBAS = { { method = "LEVEL", level = 40, species = "MILOTIC" } },
  GLIGAR = { { method = "LEVEL", level = 38, species = "GLISCOR" } },
  HAPPINY = { { method = "LEVEL", level = 15, species = "CHANSEY" } },
  IGGLYBUFF = { { method = "LEVEL", level = 10, species = "JIGGLYPUFF" } },
  KIRLIA = { { method = "ITEM", level = 1, item = "MOON_STONE", species = "GALLADE" } },
  LAMPENT = { { method = "ITEM", level = 1, item = "MOON_STONE", species = "CHANDELURE" } },
  LOMBRE = { { method = "ITEM", level = 1, item = "WATER_STONE", species = "LUDICOLO" } },
  MANTYKE = { { method = "LEVEL", level = 32, species = "MANTINE" } },
  MIME_JR = { { method = "LEVEL", level = 15, species = "MR_MIME" } },
  MINCCINO = { { method = "ITEM", level = 1, item = "MOON_STONE", species = "CINCCINO" } },
  MISDREAVUS = { { method = "ITEM", level = 1, item = "MOON_STONE", species = "MISMAGIUS" } },
  MUNCHLAX = { { method = "LEVEL", level = 20, species = "SNORLAX" } },
  MUNNA = { { method = "ITEM", level = 1, item = "MOON_STONE", species = "MUSHARNA" } },
  MURKROW = { { method = "ITEM", level = 1, item = "MOON_STONE", species = "HONCHKROW" } },
  NOSEPASS = { { method = "ITEM", level = 1, item = "THUNDER_STONE", species = "PROBOPASS" } },
  NUZLEAF = { { method = "ITEM", level = 1, item = "LEAF_STONE", species = "SHIFTRY" } },
  PANPOUR = { { method = "ITEM", level = 1, item = "WATER_STONE", species = "SIMIPOUR" } },
  PANSAGE = { { method = "ITEM", level = 1, item = "LEAF_STONE", species = "SIMISAGE" } },
  PANSEAR = { { method = "ITEM", level = 1, item = "FIRE_STONE", species = "SIMISEAR" } },
  PETILIL = { { method = "ITEM", level = 1, item = "LEAF_STONE", species = "LILLIGANT" } },
  PICHU = { { method = "LEVEL", level = 10, species = "PIKACHU" } },
  PILOSWINE = { { method = "LEVEL", level = 40, species = "MAMOSWINE" } },
  RIOLU = { { method = "LEVEL", level = 20, species = "LUCARIO" } },
  ROSELIA = { { method = "ITEM", level = 1, item = "MOON_STONE", species = "ROSERADE" } },
  SKITTY = { { method = "ITEM", level = 1, item = "MOON_STONE", species = "DELCATTY" } },
  SNEASEL = { { method = "LEVEL", level = 38, species = "WEAVILE" } },
  SNORUNT = { { method = "ITEM", level = 1, item = "MOON_STONE", species = "FROSLASS" } },
  SUNKERN = { { method = "ITEM", level = 1, item = "LEAF_STONE", species = "SUNFLORA" } },
  SWADLOON = { { method = "LEVEL", level = 20, species = "LEAVANNY" } },
  TOGEPI = { { method = "LEVEL", level = 12, species = "TOGETIC" } },
  TOGETIC = { { method = "ITEM", level = 1, item = "MOON_STONE", species = "TOGEKISS" } },
  WOOBAT = { { method = "LEVEL", level = 20, species = "SWOOBAT" } },
  YANMA = { { method = "LEVEL", level = 33, species = "YANMEGA" } },
}
