-- GENERATED by tools/build_placement.lua -- do not edit.
-- Appended wild slots for dex 152-649, scored by terrain,
-- BST-to-level fit and evolution stage.  Vanilla rows are
-- never touched: these are appended alongside them.
return {
  CERULEAN_CAVE_1F = {
    grass = { -- levels 46-53, terrain cave_deep
      {52,"BASTIODON"},{52,"BRONZONG"},{52,"EXCADRILL"},{52,"EXPLOUD"},
      {52,"GRUMPIG"},{52,"HARIYAMA"},{52,"MAMOSWINE"},{52,"RAMPARDOS"},
      {53,"ARCHEOPS"},{53,"RHYPERIOR"},
    },
  },
  CERULEAN_CAVE_2F = {
    grass = { -- levels 51-60, terrain cave_deep
      {59,"AGGRON"},{59,"CONKELDURR"},{59,"DONPHAN"},{59,"GIGALITH"},
      {59,"HIPPOWDON"},{59,"KROOKODILE"},{59,"PROBOPASS"},{59,"SCRAFTY"},
      {59,"STEELIX"},{60,"TYRANITAR"},
    },
  },
  CERULEAN_CAVE_B1F = {
    grass = { -- levels 55-67, terrain cave_deep
      {65,"CLAYDOL"},{66,"FLYGON"},{66,"GALLADE"},{66,"HAXORUS"},
      {66,"LUCARIO"},{66,"MIENSHAO"},{67,"GARCHOMP"},{67,"HYDREIGON"},
      {67,"METAGROSS"},{67,"SALAMENCE"},
    },
  },
  DIGLETTS_CAVE = {
    grass = { -- levels 15-31, terrain cave
      {19,"MAWILE"},{19,"NOSEPASS"},{21,"SOLROCK"},{22,"BOLDORE"},
      {22,"LOUDRED"},{22,"STUNFISK"},{23,"PUPITAR"},{23,"SHUCKLE"},
      {28,"CRUSTLE"},{29,"ARMALDO"},
    },
  },
  MT_MOON_1F = {
    grass = { -- levels 6-11, terrain cave
      {6,"BARBOACH"},{6,"BONSLY"},{6,"GIBLE"},{6,"LARVITAR"},{6,"MAKUHITA"},
      {6,"MEDITITE"},{6,"ROGGENROLA"},{6,"SWINUB"},{6,"WOOPER"},{7,"NUMEL"},
    },
  },
  MT_MOON_B1F = {
    grass = { -- levels 7-11, terrain cave
      {7,"BALTOY"},{7,"SANDILE"},{7,"TRAPINCH"},{7,"WYNAUT"},{8,"ARON"},
      {8,"DRILBUR"},{8,"DWEBBLE"},{8,"HIPPOPOTAS"},{8,"PHANPY"},
      {8,"SPOINK"},
    },
  },
  MT_MOON_B2F = {
    grass = { -- levels 9-12, terrain cave
      {9,"AXEW"},{9,"BELDUM"},{9,"CROAGUNK"},{9,"DEINO"},{9,"GOLETT"},
      {9,"RIOLU"},{9,"SLUGMA"},{9,"SNORUNT"},{9,"TIMBURR"},{9,"WHISMUR"},
    },
  },
  POKEMON_MANSION_1F = {
    grass = { -- levels 28-39, terrain ruin
      {29,"CHIMCHAR"},{29,"DARUMAKA"},{29,"PANSEAR"},{29,"TEPIG"},
      {30,"HOUNDOUR"},{33,"COMBUSKEN"},{33,"QUILAVA"},
    },
  },
  POKEMON_MANSION_2F = {
    grass = { -- levels 28-39, terrain ruin
      {33,"MONFERNO"},{35,"LAMPENT"},
    },
  },
  POKEMON_MANSION_3F = {
    grass = { -- levels 31-42, terrain ruin
      {36,"HEATMOR"},{37,"PIGNITE"},{40,"GARBODOR"},{40,"SKUNTANK"},
      {41,"DRAPION"},
    },
  },
  POKEMON_MANSION_B1F = {
    grass = { -- levels 31-42, terrain ruin
      {36,"TORKOAL"},{40,"DARMANITAN"},{41,"CHANDELURE"},{41,"EMBOAR"},
      {41,"HOUNDOOM"},{41,"INFERNAPE"},{41,"MAGMORTAR"},{41,"SIMISEAR"},
      {41,"TYPHLOSION"},{42,"VOLCARONA"},
    },
  },
  POKEMON_TOWER_3F = {
    grass = { -- levels 18-25, terrain haunted
      {18,"LITWICK"},{19,"ELGYEM"},{19,"SHUPPET"},{19,"UNOWN"},
      {19,"YAMASK"},
    },
  },
  POKEMON_TOWER_4F = {
    grass = { -- levels 18-25, terrain haunted
      {19,"SMOOCHUM"},{20,"KIRLIA"},
    },
  },
  POKEMON_TOWER_5F = {
    grass = { -- levels 18-25, terrain haunted
      {19,"DRIFLOON"},{19,"STUNKY"},{19,"TRUBBISH"},{21,"DUOSION"},
    },
  },
  POKEMON_TOWER_6F = {
    grass = { -- levels 19-28, terrain haunted
      {21,"SABLEYE"},
    },
  },
  POKEMON_TOWER_7F = {
    grass = { -- levels 20-30, terrain haunted
      {23,"MISDREAVUS"},{24,"ROTOM"},{24,"SPIRITOMB"},{25,"GOTHORITA"},
      {26,"DUSCLOPS"},{28,"BANETTE"},{28,"COFAGRIGUS"},{29,"DRIFBLIM"},
      {29,"DUSKNOIR"},{29,"MISMAGIUS"},
    },
  },
  POWER_PLANT = {
    grass = { -- levels 20-36, terrain industrial
      {25,"PACHIRISU"},{27,"LUXIO"},{31,"EELEKTRIK"},{34,"EELEKTROSS"},
      {34,"GARDEVOIR"},{34,"ZEBSTRIKA"},{35,"ELECTIVIRE"},{35,"ESPEON"},
      {35,"LUXRAY"},{35,"MAGNEZONE"},
    },
  },
  ROCK_TUNNEL_1F = {
    grass = { -- levels 13-18, terrain cave
      {14,"CRANIDOS"},{14,"MIENFOO"},{14,"SCRAGGY"},{14,"SHIELDON"},
      {15,"KROKOROK"},
    },
  },
  ROCK_TUNNEL_B1F = {
    grass = { -- levels 13-18, terrain cave
      {14,"ANORITH"},{14,"MAGBY"},{14,"TIRTOUGA"},{17,"SUDOWOODO"},
      {17,"WHISCASH"},
    },
  },
  ROUTE_1 = {
    grass = { -- levels 2-5, terrain grassland
      {2,"BUDEW"},{2,"BURMY"},{2,"CHERUBI"},{2,"COTTONEE"},{2,"FOONGUS"},
      {2,"KRICKETOT"},{2,"LEDYBA"},{2,"NINCADA"},{2,"PETILIL"},
      {2,"VENIPEDE"},
    },
  },
  ROUTE_10 = {
    grass = { -- levels 11-17, terrain grassland
      {12,"BUNEARY"},{12,"LILEEP"},
    },
  },
  ROUTE_11 = {
    grass = { -- levels 9-17, terrain grassland
      {10,"PAWNIARD"},{10,"TEDDIURSA"},{12,"SKIPLOOM"},{12,"STARAVIA"},
      {14,"NUZLEAF"},
    },
  },
  ROUTE_12 = {
    grass = { -- levels 22-30, terrain grassland
      {25,"AUDINO"},{25,"GIRAFARIG"},{25,"SEVIPER"},{25,"STANTLER"},
      {26,"BOUFFALANT"},{26,"MILTANK"},{26,"SIGILYPH"},{27,"ARIADOS"},
      {27,"ROSELIA"},{28,"TOGETIC"},
    },
  },
  ROUTE_13 = {
    grass = { -- levels 22-30, terrain grassland
      {26,"VIGOROTH"},{28,"MOTHIM"},{28,"PORYGON2"},{28,"SUNFLORA"},
      {28,"SWOOBAT"},{28,"WORMADAM"},{29,"AMBIPOM"},{29,"BISHARP"},
      {29,"LOPUNNY"},{29,"STOUTLAND"},
    },
  },
  ROUTE_14 = {
    grass = { -- levels 22-30, terrain grassland
      {28,"NINJASK"},{28,"NOCTOWL"},{28,"SWELLOW"},{29,"BRAVIARY"},
      {29,"CINCCINO"},{29,"FERROTHORN"},{29,"GALVANTULA"},{29,"HONCHKROW"},
      {29,"UMBREON"},{30,"BLISSEY"},
    },
  },
  ROUTE_15 = {
    grass = { -- levels 22-30, terrain grassland
      {28,"AMOONGUSS"},{28,"PURUGLY"},{29,"LEAFEON"},{29,"LEAVANNY"},
      {29,"SCOLIPEDE"},{29,"SIMISAGE"},{29,"STARAPTOR"},{29,"TANGROWTH"},
      {29,"TORTERRA"},{29,"YANMEGA"},
    },
  },
  ROUTE_16 = {
    grass = { -- levels 18-25, terrain grassland
      {20,"VULLABY"},{21,"HERDIER"},
    },
  },
  ROUTE_17 = {
    grass = { -- levels 20-29, terrain grassland
      {26,"DUSTOX"},{26,"KRICKETUNE"},{26,"SWADLOON"},
    },
  },
  ROUTE_18 = {
    grass = { -- levels 20-29, terrain grassland
      {23,"ARCHEN"},{23,"CHATOT"},{23,"EMOLGA"},{23,"KECLEON"},{23,"MINUN"},
      {23,"PLUSLE"},{24,"ABSOL"},{24,"BAYLEEF"},{24,"SKARMORY"},
      {24,"ZANGOOSE"},
    },
  },
  ROUTE_19 = {
    water = { -- levels 5-40, terrain water
      {5,"FEEBAS"},{8,"REMORAID"},{8,"SPHEAL"},{9,"CORPHISH"},{9,"MUDKIP"},
      {10,"LUVDISC"},{11,"CLAMPERL"},{15,"WAILMER"},{22,"CROCONAW"},
      {31,"PELIPPER"},
    },
  },
  ROUTE_2 = {
    grass = { -- levels 2-5, terrain grassland
      {2,"COMBEE"},{2,"IGGLYBUFF"},{2,"MAREEP"},{2,"PICHU"},{2,"POOCHYENA"},
      {2,"SMEARGLE"},{2,"SNIVY"},{2,"SNUBBULL"},{2,"SUNKERN"},
      {2,"ZIGZAGOON"},
    },
  },
  ROUTE_20 = {
    water = { -- levels 5-40, terrain water
      {5,"LOTAD"},{6,"WINGULL"},{9,"CARVANHA"},{10,"CHINCHOU"},
      {17,"QWILFISH"},{30,"AZUMARILL"},{33,"CRAWDAUNT"},{33,"SHARPEDO"},
      {34,"MANTINE"},{34,"OCTILLERY"},
    },
  },
  ROUTE_21 = {
    grass = { -- levels 21-32, terrain grassland
      {30,"BELLOSSOM"},{30,"BRELOOM"},{30,"GRANBULL"},{30,"JUMPLUFF"},
      {30,"MANECTRIC"},{30,"SAWSBUCK"},{30,"UNFEZANT"},{30,"VESPIQUEN"},
      {31,"MANDIBUZZ"},{32,"SLAKING"},
    },
    water = { -- levels 5-40, terrain water
      {6,"SURSKIT"},{9,"TOTODILE"},{11,"MANTYKE"},{12,"MARILL"},
      {19,"ALOMOMOLA"},{19,"BASCULIN"},{25,"LOMBRE"},{34,"GOREBYSS"},
      {34,"HUNTAIL"},{34,"LUDICOLO"},
    },
  },
  ROUTE_22 = {
    grass = { -- levels 2-5, terrain grassland
      {2,"DUSKULL"},{2,"ELECTRIKE"},{2,"FERROSEED"},{2,"HOOTHOOT"},
      {2,"SENTRET"},{2,"SHELMET"},{2,"SKITTY"},{2,"STARLY"},{2,"TAILLOW"},
      {2,"TOGEPI"},
    },
  },
  ROUTE_23 = {
    grass = { -- levels 26-43, terrain grassland
      {32,"ILLUMISE"},{32,"VOLBEAT"},{34,"HERACROSS"},{41,"GLISCOR"},
      {41,"KLINKLANG"},{41,"LICKILICKY"},{41,"ZOROARK"},{42,"BLAZIKEN"},
      {42,"PORYGON_Z"},{42,"TOGEKISS"},
    },
  },
  ROUTE_24 = {
    grass = { -- levels 7-14, terrain grassland
      {8,"CACNEA"},{8,"CHIKORITA"},{8,"DEERLING"},{8,"JOLTIK"},
      {8,"MIME_JR"},{8,"NATU"},{8,"SNOVER"},{8,"SOLOSIS"},{8,"WOOBAT"},
      {8,"ZORUA"},
    },
  },
  ROUTE_25 = {
    grass = { -- levels 7-14, terrain grassland
      {7,"AZURILL"},{7,"CHINGLING"},{7,"CLEFFA"},{7,"RALTS"},{7,"TYROGUE"},
      {8,"BRONZOR"},{8,"GOTHITA"},{8,"MUNNA"},{8,"SWABLU"},{8,"TORCHIC"},
    },
  },
  ROUTE_3 = {
    grass = { -- levels 3-8, terrain grassland
      {3,"BIDOOF"},{3,"GULPIN"},{3,"HAPPINY"},{3,"LILLIPUP"},{3,"PATRAT"},
      {3,"SHINX"},{3,"SLAKOTH"},{4,"KARRABLAST"},{4,"PANSAGE"},
      {4,"TURTWIG"},
    },
  },
  ROUTE_4 = {
    grass = { -- levels 6-12, terrain grassland
      {6,"HOPPIP"},{6,"PIDOVE"},{6,"PURRLOIN"},{6,"TYNAMO"},{7,"BLITZLE"},
      {7,"CYNDAQUIL"},{7,"GLAMEOW"},{7,"KLINK"},{7,"MINCCINO"},
      {7,"SKORUPI"},
    },
  },
  ROUTE_7 = {
    grass = { -- levels 17-22, terrain grassland
      {19,"FLAAFFY"},{19,"WHIRLIPEDE"},
    },
  },
  ROUTE_8 = {
    grass = { -- levels 15-20, terrain grassland
      {16,"AIPOM"},{16,"ELEKID"},{16,"LARVESTA"},{16,"SPINDA"},
      {17,"TRANQUILL"},
    },
  },
  ROUTE_9 = {
    grass = { -- levels 11-17, terrain grassland
      {12,"RUFFLET"},
    },
  },
  SAFARI_ZONE_CENTER = {
    grass = { -- levels 22-31, terrain grassland
      {24,"YANMA"},{25,"CARNIVINE"},{26,"DURANT"},{26,"MARACTUS"},
      {26,"TROPIUS"},{27,"KLANG"},{27,"LINOONE"},{28,"FURRET"},
      {28,"MIGHTYENA"},{28,"WATCHOG"},
    },
  },
  SAFARI_ZONE_EAST = {
    grass = { -- levels 22-33, terrain grassland
      {25,"MUNCHLAX"},{25,"MURKROW"},{26,"CASTFORM"},{27,"GROTLE"},
      {27,"GROVYLE"},{28,"SERVINE"},{29,"BEAUTIFLY"},{29,"DELCATTY"},
      {29,"LEDIAN"},
    },
  },
  SAFARI_ZONE_NORTH = {
    grass = { -- levels 22-32, terrain grassland
      {30,"CACTURNE"},{30,"CHERRIM"},{30,"LIEPARD"},{30,"LILLIGANT"},
      {30,"WHIMSICOTT"},{31,"ACCELGOR"},{31,"CRADILY"},{31,"ESCAVALIER"},
      {31,"ROSERADE"},{31,"SERPERIOR"},
    },
  },
  SAFARI_ZONE_WEST = {
    grass = { -- levels 23-33, terrain grassland
      {31,"CHIMECHO"},{31,"FORRETRESS"},{31,"MASQUERAIN"},{31,"SHIFTRY"},
      {31,"SWALOT"},{31,"XATU"},{32,"AMPHAROS"},{32,"MEGANIUM"},
      {32,"SCEPTILE"},{32,"SCIZOR"},
    },
  },
  SEAFOAM_ISLANDS_1F = {
    grass = { -- levels 21-38, terrain ice_cave
      {22,"TYMPOLE"},{23,"DUCKLETT"},{23,"OSHAWOTT"},{23,"PANPOUR"},
      {23,"PIPLUP"},{23,"SHELLOS"},{24,"BUIZEL"},{24,"FINNEON"},
      {24,"FRILLISH"},{29,"VANILLISH"},
    },
  },
  SEAFOAM_ISLANDS_B1F = {
    grass = { -- levels 28-38, terrain ice_cave
      {31,"CORSOLA"},{35,"QUAGSIRE"},{36,"GLALIE"},{36,"JELLICENT"},
      {37,"EMPOLEON"},{37,"FLOATZEL"},{37,"KINGDRA"},{37,"SAMUROTT"},
      {37,"SEISMITOAD"},{37,"SIMIPOUR"},
    },
  },
  SEAFOAM_ISLANDS_B2F = {
    grass = { -- levels 28-37, terrain ice_cave
      {29,"CUBCHOO"},{29,"DELIBIRD"},{29,"VANILLITE"},{32,"MARSHTOMP"},
      {32,"PALPITOAD"},{32,"PRINPLUP"},{35,"FROSLASS"},{35,"GASTRODON"},
      {36,"ABOMASNOW"},{36,"SWAMPERT"},
    },
  },
  SEAFOAM_ISLANDS_B3F = {
    grass = { -- levels 29-39, terrain ice_cave
      {33,"RELICANTH"},{34,"DEWOTT"},{37,"LANTURN"},{37,"SWANNA"},
      {38,"FERALIGATR"},{38,"MILOTIC"},{38,"POLITOED"},{38,"SLOWKING"},
      {38,"WAILORD"},{38,"WALREIN"},
    },
  },
  SEAFOAM_ISLANDS_B4F = {
    grass = { -- levels 29-39, terrain ice_cave
      {32,"SNEASEL"},{34,"CRYOGONAL"},{34,"SEALEO"},{36,"BIBAREL"},
      {37,"LUMINEON"},{38,"BEARTIC"},{38,"CARRACOSTA"},{38,"GLACEON"},
      {38,"VANILLUXE"},{38,"WEAVILE"},
    },
  },
  VICTORY_ROAD_1F = {
    grass = { -- levels 22-43, terrain cave_deep
      {28,"DUNSPARCE"},{29,"GLIGAR"},{30,"LUNATONE"},{30,"SAWK"},
      {30,"THROH"},{33,"LAIRON"},{37,"MAGCARGO"},{38,"HITMONTOP"},
      {38,"PILOSWINE"},{39,"CAMERUPT"},
    },
  },
  VICTORY_ROAD_2F = {
    grass = { -- levels 22-43, terrain cave_deep
      {24,"BAGON"},{30,"VIBRAVA"},{32,"GURDURR"},{33,"FRAXURE"},
      {33,"GABITE"},{33,"METANG"},{33,"SHELGON"},{33,"ZWEILOUS"},
      {37,"MEDICHAM"},{37,"WOBBUFFET"},
    },
  },
  VICTORY_ROAD_3F = {
    grass = { -- levels 22-45, terrain cave_deep
      {32,"DRUDDIGON"},{41,"BEHEEYEM"},{41,"GOLURK"},{41,"MUSHARNA"},
      {42,"ALTARIA"},{42,"GOTHITELLE"},{42,"REUNICLUS"},{42,"TOXICROAK"},
      {42,"URSARING"},{43,"CROBAT"},
    },
  },
  VIRIDIAN_FOREST = {
    grass = { -- levels 3-6, terrain forest
      {3,"PINECO"},{3,"SEEDOT"},{3,"SEWADDLE"},{3,"SHROOMISH"},
      {3,"SPINARAK"},{3,"TREECKO"},{3,"WURMPLE"},{4,"CASCOON"},
      {4,"SHEDINJA"},{4,"SILCOON"},
    },
  },
}
