#!/usr/bin/env python3
"""
Bundle src/*.lua and data/*.lua into a single-file main.lua.

WHY THIS EXISTS
---------------
A mod-relative `require` does not resolve at runtime in Gen1Recomp. The
loader does `chunk(api)` on the entry file (src/mods/Loader.lua:1157) with
LOVE's package path pointing at the GAME, not at the mod, so
`require("data.species")` throws on the first line. Requiring ENGINE modules
(`require("src.core.Strings")`) works fine -- those are on the game's path.
gen1recomp-modern-kanto hit the same wall and ships one flat main.lua as a
result.

The engine does expose `mod:read(relative)`, and data could be loaded with
`load(mod:read(...))`. This bundler inlines instead, deliberately: inlining
depends on no runtime API at all, so it cannot break on an engine build where
`mod:read` is older, absent or sandboxed. The cost is a large main.lua, which
is irrelevant next to 4 MB of sprites.

Development stays modular -- edit src/ and data/, then run this.

Modules keep their `require` shape via a tiny registry, so the inlined bodies
are byte-identical to the standalone files and the offline test can exercise
either form.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

# Inlined in dependency order: data has no deps, then leaf modules, then the
# ones that reference them.
MODULES = [
    ("data.moves", "data/moves.lua"),
    ("data.retro", "data/retro.lua"),
    ("data.species", "data/species.lua"),
    ("src.growth_rates", "src/growth_rates.lua"),
    ("src.moves", "src/moves.lua"),
    ("src.encounters", "src/encounters.lua"),
]

PRELUDE = '''-- =====================================================================
-- Dex Expansion (Gen 2-5) for Gen1Recomp -- GENERATED SINGLE FILE
--
-- Do not edit this file. Edit src/*.lua and data/*.lua, then run
--     python3 tools/bundle.py
--
-- Everything is inlined because a mod-relative `require` does not resolve at
-- runtime: the loader runs this file with LOVE's package path pointing at the
-- game, not at the mod, so `require("data.species")` throws immediately.
-- Engine requires still work; mod-relative ones never do.
--
-- `__dexpand_require` below stands in for `require` so the inlined module
-- bodies stay byte-identical to their standalone source files.
-- =====================================================================

local __dexpand_loaders = {}
local __dexpand_cache = {}

local function __dexpand_require(name)
  local hit = __dexpand_cache[name]
  if hit ~= nil then return hit end
  local loader = __dexpand_loaders[name]
  if not loader then
    -- not one of ours: fall through to the engine's real require, which is
    -- how a mod reaches src.core.* and friends
    return require(name)
  end
  local value = loader()
  __dexpand_cache[name] = value
  return value
end

'''


def wrap(name: str, body: str) -> str:
    # Rewrite only mod-relative requires; engine requires must stay untouched.
    body = re.sub(r'require\(\s*"((?:data|src)\.[A-Za-z0-9_.]+)"\s*\)',
                  r'__dexpand_require("\1")', body)
    indented = "\n".join(("  " + ln) if ln.strip() else ln
                         for ln in body.splitlines())
    return (f'__dexpand_loaders["{name}"] = function()\n'
            f'{indented}\nend\n\n')


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--entry", default="src/main_entry.lua",
                    help="the modular entry body to append last")
    ap.add_argument("--out", default="main.lua")
    args = ap.parse_args(argv)

    root = Path(args.root)
    parts = [PRELUDE]
    for name, rel in MODULES:
        path = root / rel
        if not path.exists():
            raise SystemExit(f"missing module: {rel}")
        parts.append(wrap(name, path.read_text(encoding="utf-8")))

    entry = (root / args.entry).read_text(encoding="utf-8")
    entry = re.sub(r'require\(\s*"((?:data|src)\.[A-Za-z0-9_.]+)"\s*\)',
                   r'__dexpand_require("\1")', entry)
    parts.append("-- ================= entry chunk =================\n")
    parts.append(entry)

    out = root / args.out
    out.write_text("".join(parts), encoding="utf-8")
    kb = out.stat().st_size / 1024
    print(f"bundled {len(MODULES)} modules + entry -> {out} ({kb:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
