-- Compatibility with swuff-star/KEP-Recomp-Port.
--
-- KEP is a total conversion that rebuilds Kanto: it renumbers the whole dex,
-- adds 100 species (beta mons and later-gen additions), and hand-authors every
-- encounter table.  Read from its own source, it does:
--
--     mod.content.pokemon:patch     x151   renumbers the vanilla roster
--     mod.content.pokemon:register  x100   its own species, dex 1..251
--     mod.content.encounters:override x254 every table, wholesale
--     mod.content.cries:register    x100
--     mod.content.constants:patch   x2     dexSize
--
-- Three separate collisions come out of that, and only one of them is about
-- dex numbers.
--
-- 1. TWENTY SHARED SPECIES IDS.  Both mods register these.  `pokemon` is a
--    record registry and Registry:register errors outright on a duplicate:
--
--        if self.spec.semantics == "record" and self:get(id) ~= nil then
--          error(("%s already registered: %s"):format(self.name, id))
--
--    Load order is priority then id, and "dex_expansion" sorts before "kep",
--    so we register first and KEP's call is the one that throws.  KEP's
--    loadContent does not pcall, so the whole mod fails to load.  We break
--    KEP, not the other way round.  Same story for its 100 cry registers.
--
--    So we stand down on those twenty: KEP's versions are authored for its
--    world and should win.  Existence is still unconditional -- the species
--    exist, KEP just provides them -- so nothing a save knows disappears.
--
-- 2. ENCOUNTERS.  KEP overrides all 254 tables with hand-built lists.  Our
--    registry patch is recorded before its override and is simply erased by
--    it, which is fine -- but our live-Data pass at game.ready runs after all
--    merging and would happily append ten of our species into its curated
--    Route 1.  Placement is therefore switched off entirely when KEP is
--    present.  A hand-authored table beats a heuristic one.
--
-- 3. DEX NUMBERS.  KEP occupies 1..251; we occupy 152..649, so 152..251 is
--    contested.  PokedexMenu builds its index as
--
--        for species, def in pairs(game.data.pokemon) do
--          if def.dex then byDex[def.dex] = def end
--
--    which is last-writer-wins over an undefined pairs() order, so a contested
--    slot would show either mon and could differ between boots.  Shifting our
--    numbers above KEP's highest removes the contest.  This does NOT create
--    duplicates: it removes them.  Every species keeps exactly one dex number,
--    and the dex flags in a save are keyed by species id rather than number,
--    so renumbering costs display order and nothing else.

local Kep = {}

Kep.MOD_ID = "kep"

-- Registered by both mods.  Generated by diffing KEP's
-- content/pokemon/generated against data/species.lua, not by hand.
Kep.SHARED_SPECIES = [[
BELLOSSOM BLISSEY CROBAT ELECTIVIRE ESPEON GLACEON HITMONTOP KINGDRA
LEAFEON LICKILICKY MAGMORTAR MAGNEZONE POLITOED PORYGON2 RHYPERIOR
SCIZOR SLOWKING STEELIX TANGROWTH UMBREON
]]

function Kep.sharedSet()
  local out = {}
  for id in Kep.SHARED_SPECIES:gmatch("[A-Z0-9_]+") do out[id] = true end
  return out
end

-- Is KEP installed?  mod.find is the only handle we get at entry time; its
-- content is not readable then, because it loads after us.
function Kep.detect(mod)
  return (mod.find and mod.find(Kep.MOD_ID)) and true or false
end

-- Shift our dex numbers above everything a foreign mod occupies.
--
-- Runs at game.ready, where the merged dataset is finally readable, so the
-- offset is measured rather than hardcoded: whatever KEP's highest number
-- turns out to be, ours start one past it.  `ours` is the set of species ids
-- this mod registered.
--
-- Returns (shifted, offset, foreignMax).
function Kep.renumber(pokemon, ours, firstOwnDex)
  if type(pokemon) ~= "table" then return 0, 0, 0 end
  local foreignMax = 0
  for id, def in pairs(pokemon) do
    if not ours[id] and type(def) == "table"
        and type(def.dex) == "number" and def.dex > foreignMax then
      foreignMax = def.dex
    end
  end
  -- nothing foreign reaches into our range, so there is nothing to dodge
  if foreignMax < firstOwnDex then return 0, 0, foreignMax end
  local offset = foreignMax - firstOwnDex + 1
  local shifted = 0
  for id, def in pairs(pokemon) do
    if ours[id] and type(def) == "table" and type(def.dex) == "number" then
      def.dex = def.dex + offset
      shifted = shifted + 1
    end
  end
  return shifted, offset, foreignMax
end

return Kep
